In [57]:
%matplotlib inline
import sqlalchemy
from sqlalchemy import create_engine,func
from sqlalchemy.orm import sessionmaker
#import mysql.connector
import pandas as pd
import numpy as np

import jieba as jb
import re

In [58]:
engine = create_engine('mysql+mysqlconnector://root:24976904@192.168.8.13:3306/owersales', echo=False)
itemsql="select ItemClsCode,itemclsname,ItemCode,ItemName,unit,MainSupcode from products WHERE ItemClsCode NOT like '23%'"
products = pd.read_sql(itemsql, engine)
products.to_csv('data/products.csv',encoding='utf-8', index=False)
products.head(10)

,ItemClsCode,itemclsname,ItemCode,ItemName,unit,MainSupcode
0,0126,低温液态奶,6941704416909,新希望源态酪乳芝士浓缩酸奶100g*10,袋,1065
1,0307,内裤,6972310095240,壮狼冰丝男士精品内裤 z5924,条,2019
2,070201,活鱼,00001,大黑鱼,kg,3013
3,070201,活鱼,00002,小黑鱼,kg,3013
4,070201,活鱼,00003,鲶鱼,kg,3013
5,070201,活鱼,00004,大青鱼,kg,3013
6,070201,活鱼,00005,鳊鱼,kg,3013
7,070201,活鱼,00006,白鲢鱼,kg,3013
8,070201,活鱼,00007,花鲢鱼,kg,3013
9,070201,活鱼,00008,小草鱼,kg,3013

# 移除生鲜类别

In [59]:
products = products[~products['ItemClsCode'].str.startswith('07')]
products.head(10)

,ItemClsCode,itemclsname,ItemCode,ItemName,unit,MainSupcode
0,0126,低温液态奶,6941704416909,新希望源态酪乳芝士浓缩酸奶100g*10,袋,1065
1,0307,内裤,6972310095240,壮狼冰丝男士精品内裤 z5924,条,2019
519,01,食品,01,食品,,9999
520,0814,散称零食,01001,雀巢威化散称,kg,1042
521,0814,散称零食,01002,粗粮脆锅巴猫耳朵,kg,1038
522,0814,散称零食,01003,散称泡吧糕点系列,kg,1038
523,0814,散称零食,01004,友臣糕点系列,kg,1038
524,0806,点心,01005,盼盼手撕面包散称,kg,1035
525,0813,散称坚果,01006,甘源炒货系列散称,kg,1035
526,0806,点心,01007,耶米熊系列散称,kg,1035

In [60]:
#去除商品过少的分类
d={'cat':products['ItemClsCode'].value_counts().index,'count':products['ItemClsCode'].value_counts()}

df_cat=pd.DataFrame(data=d)
df_cat.loc[df_cat['count']<10][['cat','count']].values

array([['021202      ', 9],
       ['040401      ', 9],
       ['012404      ', 9],
       ['011502      ', 9],
       ['021505      ', 9],
       ['011003      ', 8],
       ['020506      ', 8],
       ['0810        ', 8],
       ['010803      ', 7],
       ['0508        ', 7],
       ['0809        ', 7],
       ['021901      ', 6],
       ['0124        ', 6],
       ['0222        ', 6],
       ['0811        ', 6],
       ['020806      ', 6],
       ['020605      ', 5],
       ['051501      ', 5],
       ['040407      ', 5],
       ['022104      ', 5],
       ['040403      ', 4],
       ['040405      ', 4],
       ['060110      ', 3],
       ['020405      ', 2],
       ['0820        ', 2],
       ['18          ', 2],
       ['2202        ', 2],
       ['040402      ', 2],
       ['022205      ', 2],
       ['052005      ', 2],
       ['022109      ', 2],
       ['0807        ', 1],
       ['0409        ', 1],
       ['040406      ', 1],
       ['02          ', 1],
       ['021410      ', 1],
       ['01          ', 1],
       ['0113        ', 1],
       ['040802      ', 1],
       ['040602      ', 1]], dtype=object)

In [61]:
index_to_drop = df_cat.query('count < 10').index
index_to_drop

Index(['021202      ', '040401      ', '012404      ', '011502      ',
       '021505      ', '011003      ', '020506      ', '0810        ',
       '010803      ', '0508        ', '0809        ', '021901      ',
       '0124        ', '0222        ', '0811        ', '020806      ',
       '020605      ', '051501      ', '040407      ', '022104      ',
       '040403      ', '040405      ', '060110      ', '020405      ',
       '0820        ', '18          ', '2202        ', '040402      ',
       '022205      ', '052005      ', '022109      ', '0807        ',
       '0409        ', '040406      ', '02          ', '021410      ',
       '01          ', '0113        ', '040802      ', '040602      '],
      dtype='object', name='ItemClsCode')

In [62]:
products = products[~products['ItemClsCode'].isin(index_to_drop)]

In [63]:
dalei_df=pd.read_csv('data/allleibei.csv',dtype={"itemclscode": str})
dalei_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 629 entries, 0 to 628
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   itemclscode  629 non-null    object
 1   ClassName    629 non-null    object
dtypes: object(2)
memory usage: 10.0+ KB

In [64]:
products.loc[:,'cat_id'] = products['ItemClsCode'].factorize()[0]
cat_id_df = products[['ItemClsCode', 'cat_id']].drop_duplicates().sort_values('cat_id').reset_index(drop=True)
cat_to_id = dict(cat_id_df.values)
id_to_cat = dict(cat_id_df[['cat_id', 'ItemClsCode']].values)
cat_id_df['ItemClsCode']=cat_id_df['ItemClsCode'].str.strip()
cat_id_df=pd.merge(left=cat_id_df,right=dalei_df,how='left',left_on='ItemClsCode',right_on='itemclscode')
cat_id_df.drop('itemclscode',axis=1, inplace=True)
id_to_cat_name = dict(cat_id_df[['cat_id', 'ClassName']].values)
cat_id_df.to_csv('data/cat_small_id_df.csv',encoding='utf-8', index=False)

In [65]:
cat_id_df

    ItemClsCode  cat_id ClassName
0          0126       0     低温液态奶
1          0307       1        内裤
2          0814       2      散称零食
3          0806       3        点心
4          0813       4      散称坚果
..          ...     ...       ...
241      040201     241        灯具
242      052006     242       灭蚊器
243      021303     243    浴室五金配件
244      051201     244      灶具用品
245      050101     245   音乐播放器附件

[246 rows x 3 columns]

In [66]:
def getClassName(code):
    return id_to_cat[code].strip() + "-" + id_to_cat_name[code]

In [67]:
getClassName(0)

'0126-低温液态奶'

In [68]:
remove_chars = '`~!@#$%^&*()-=_+[]{}\\|;\':",./<>?' + \
    '·！@#￥%……&*（）——【】、『』|；‘’：“”，。《》？'
trans_table = dict([(ord(c), None) for c in remove_chars])
jb.load_userdict('data/productnames.dict')

In [69]:

def preprocess(cells):
    #print(count)
    cells['ItemCode']=cells['ItemCode'][0:8]

    # remove punctuation
    # fillna is not reliable, unicode(cell) is necessary
    cleaned = [str(cell).translate(trans_table) for cell in cells.values]
    # chinese segment
    segmented = [u' '.join(jb.cut(cell)) for cell in cleaned]
    return u' '.join(segmented)

In [70]:
products.loc[:,'preprocessed'] = products[['ItemCode','ItemName','unit','MainSupcode']] \
    .apply(preprocess, axis=1)

In [71]:
products

,ItemClsCode,itemclsname,ItemCode,ItemName,unit,MainSupcode,cat_id,preprocessed
0,0126,低温液态奶,6941704416909,新希望源态酪乳芝士浓缩酸奶100g*10,袋,1065,0,6941704 新 希望 源态 酪 乳 芝士 浓缩 酸奶 100g10 袋 10...
1,0307,内裤,6972310095240,壮狼冰丝男士精品内裤 z5924,条,2019,1,6972310 壮狼 冰丝 男士 精品 内裤 z5924 条 2019 ...
520,0814,散称零食,01001,雀巢威化散称,kg,1042,2,01001 雀巢 威化 散称 kg 1042
521,0814,散称零食,01002,粗粮脆锅巴猫耳朵,kg,1038,2,01002 粗粮 脆 锅巴 猫 耳朵 kg 1038
522,0814,散称零食,01003,散称泡吧糕点系列,kg,1038,2,01003 散称 泡吧 糕点 系列 kg 1038
...,...,...,...,...,...,...,...,...
50266,012803,春节年货,99990018,尊享年货礼盒,盒,9999,21,99990018 尊 享年 货 礼盒 盒 9999
50267,20,超市耗材,99990019,5元换购商品,个,9999,23,99990019 5 元 换购 商品 个 9999
50268,012801,端午粽子,99990020,俏粽娘粽子,袋,1071,149,99990020 俏 粽娘 粽子 袋 1071
50269,20,超市耗材,99990021,10元换购商品,个,9999,23,99990021 10 元 换购 商品 个 9999
50270,012803,春节年货,999902,1.62kg旺旺果冻礼盒,袋,1038,21,999902 162kg 旺旺 果冻 礼盒 袋 1038

In [72]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

In [73]:
vectorizer = TfidfVectorizer(decode_error='ignore', ngram_range=(1, 2),min_df=5, max_df=0.5,token_pattern=r"(?u)\b\w+\b")

In [74]:
X = vectorizer.fit_transform(products.preprocessed)
y = products.cat_id

X_train, X_test, y_train, y_test,indices_train, indices_test = train_test_split(X, y,products.index, random_state = 0,stratify=y)

In [75]:
X.shape

(47502, 19225)

In [76]:
clf = LinearSVC(dual=False)

In [77]:
clf.fit(X_train,y_train)

LinearSVC(dual=False)

In [78]:
y_pred = clf.predict(X_test)

In [79]:
y_pred

array([163,  31,  50, ...,  61,  41,   0], dtype=int64)

In [80]:
import joblib
joblib.dump(vectorizer,'data/Tfidf_min_vect.pkl')
joblib.dump(clf,'data/clf_min_model.pkl')
# 合并模型
#from sklearn.pipeline import Pipeline

# 创建 pipeline
#model_pipeline = Pipeline([
#    ('vectorizer', vectorizer),
#    ('classifier', clf)
#])

# 保存整个 pipeline
#joblib.dump(model_pipeline, 'data/model_pipeline.pkl')

['data/clf_min_model.pkl']

In [81]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

print('accuracy %s' % accuracy_score(y_pred, y_test))
report = classification_report(y_test, y_pred,target_names=cat_id_df['ItemClsCode'].values,output_dict=True)
print(classification_report(y_test, y_pred,target_names=cat_id_df['ItemClsCode'].values))

for class_name, metrics in report.items():
    if isinstance(metrics, dict) and metrics['precision'] < 0.6:
        print(f"Class: {class_name}")
        print(f"Precision: {metrics['precision']}")
        print(f"Recall: {metrics['recall']}")
        print(f"F1-score: {metrics['f1-score']}")
        print(f"Support: {metrics['support']}")
        print("-------------------------------")

accuracy 0.9481306837318962
              precision    recall  f1-score   support

        0126       0.99      1.00      0.99       241
        0307       0.99      0.98      0.98        83
        0814       0.60      0.18      0.27        17
        0806       0.57      0.86      0.69        14
        0813       0.50      0.33      0.40         6
        0801       0.80      0.73      0.76        11
        0812       0.50      0.33      0.40         3
        0803       0.43      0.38      0.40         8
        0818       0.50      0.44      0.47         9
        0805       0.96      1.00      0.98        22
      012802       0.97      1.00      0.98        61
        0808       0.62      0.71      0.67         7
      012302       0.91      0.95      0.93       289
      012406       1.00      0.83      0.91        18
      020504       0.71      0.77      0.74        39
        0130       0.89      0.67      0.76        24
      012102       1.00      1.00      1.00         3
      022208       1.00      1.00      1.00        10
      060114       0.89      0.80      0.84        10
        0816       1.00      1.00      1.00        12
      012701       0.98      0.98      0.98       129
      012803       0.84      0.84      0.84        88
      012001       1.00      0.87      0.93        15
          20       0.67      0.80      0.73         5
        0309       0.96      0.88      0.91        49
      030103       0.67      0.83      0.74        12
        0305       0.99      0.99      0.99        90
      030702       0.94      0.85      0.89        20
      010901       1.00      0.96      0.98        28
      011902       0.98      0.95      0.97        59
      010701       0.94      0.94      0.94        89
      010605       0.90      0.97      0.94       278
      010401       0.93      0.97      0.95        78
      010501       0.98      0.99      0.98        87
      011601       0.92      0.98      0.95       138
      011501       0.97      0.95      0.96       108
        2102       1.00      1.00      1.00        10
      011901       0.99      0.98      0.99       174
        1501       0.96      0.99      0.98       446
      021208       1.00      1.00      1.00        53
      011605       0.89      0.89      0.89        61
        2101       1.00      1.00      1.00       251
        0602       1.00      0.75      0.86         4
        2203       0.67      1.00      0.80         2
      020404       1.00      0.86      0.92         7
      022305       0.90      0.90      0.90        51
      052007       1.00      1.00      1.00         4
      052001       1.00      1.00      1.00        14
        2103       1.00      1.00      1.00        29
        1701       1.00      0.99      0.99        76
        1502       1.00      0.99      0.99      1378
      011802       0.78      0.78      0.78         9
      011801       0.93      0.97      0.95        58
        1702       0.99      1.00      1.00       129
      012204       0.97      0.96      0.96        69
        0304       0.93      1.00      0.97        14
      022004       1.00      1.00      1.00         8
      011701       0.96      0.79      0.87        29
        0401       0.92      1.00      0.96        12
      012303       0.95      0.95      0.95        97
      011702       0.92      1.00      0.96        48
      012202       0.97      0.94      0.96       124
      022207       1.00      1.00      1.00        10
        1703       1.00      1.00      1.00       337
      012301       0.95      0.90      0.93       210
      011604       0.91      0.85      0.88       102
      012203       0.98      0.96      0.97        47
      012401       0.90      0.87      0.89        76
      010702       0.89      0.90      0.90        93
        0132       0.92      0.95      0.93       183
      011603       0.95      0.92      0.93       130
      022112       1.00      1.00      1.00       119
      022110       0.99      1.00      0.99        70
      022105       1.00      1.00      1.00         4
      012705       1.00      0.96      0.98        25
      012703       0.96      0.98      0.97        54
      010615       1.00      0.93      0.96        14
      010602       0.89      0.73      0.80        64
      011201       0.91      0.91      0.91        11
      010619       0.81      0.94      0.87        32
      010616       0.89      0.96      0.93        26
      010614       0.92      0.95      0.93        37
      012405       0.96      0.97      0.96       272
      012201       0.86      0.96      0.91        25
      011101       0.96      0.96      0.96        45
      012402       0.90      0.95      0.93        40
      012205       0.99      1.00      0.99       174
      012305       1.00      0.83      0.91         6
      012304       0.97      0.94      0.95        32
        0220       1.00      1.00      1.00        14
      011002       0.86      0.78      0.82        23
      011609       0.85      0.93      0.89        30
        0815       0.50      0.57      0.53         7
      012403       0.96      0.97      0.97        71
      040408       1.00      0.80      0.89         5
      012704       0.93      0.92      0.92        96
      011102       0.80      0.96      0.87        25
      010403       1.00      0.91      0.95        22
      012308       1.00      1.00      1.00        14
      010404       0.97      0.99      0.98        67
      011903       1.00      1.00      1.00        11
      011401       0.80      0.89      0.84         9
      022302       0.91      1.00      0.95        10
        0209       0.88      0.93      0.91        90
      022307       0.90      0.96      0.93        28
      022304       1.00      0.90      0.95        30
      022306       1.00      0.80      0.89        10
      011602       0.91      1.00      0.95        29
      022201       0.67      0.86      0.75        14
      022203       0.80      0.80      0.80        25
      022101       0.98      0.98      0.98        66
      022111       0.96      0.96      0.96        25
      022103       0.94      1.00      0.97        75
      021701       0.80      0.67      0.73         6
      021804       0.94      1.00      0.97        33
      021801       0.99      0.97      0.98       131
      021705       0.89      0.87      0.88        46
      020703       0.89      0.89      0.89        45
      041001       0.86      1.00      0.92         6
      021702       0.94      0.97      0.95        61
      011004       0.89      0.88      0.88        65
      021704       0.95      1.00      0.97        54
      021706       1.00      0.89      0.94         9
      021703       0.90      0.82      0.86        22
      011301       0.93      0.81      0.87        16
      021803       0.79      0.79      0.79        14
      022108       0.76      0.93      0.84        14
      010611       0.76      0.96      0.85        23
      010612       1.00      0.69      0.82        13
      010610       1.00      0.67      0.80         9
      010618       0.91      0.94      0.92        31
      010613       0.96      0.83      0.89        30
      012902       1.00      0.70      0.82        10
      021802       0.96      0.89      0.92        27
      011606       0.94      0.80      0.86        40
      010805       1.00      0.93      0.96        14
      022106       0.88      0.88      0.88         8
      022102       1.00      0.33      0.50         6
      012206       0.98      1.00      0.99        54
        2201       0.97      1.00      0.99        66
      010405       0.95      0.98      0.96        54
      010606       1.00      0.69      0.81        16
      010201       0.95      0.99      0.97        79
      010202       0.88      0.78      0.82        18
      012501       1.00      0.88      0.93         8
      022301       1.00      0.99      1.00       117
        0306       1.00      1.00      1.00        12
      011103       0.67      1.00      0.80        10
      012706       0.95      0.92      0.93       101
      012801       0.84      0.84      0.84        19
      022107       1.00      1.00      1.00         3
      051601       0.92      0.92      0.92        26
      040102       1.00      1.00      1.00         4
      011904       0.91      0.91      0.91        11
      010402       1.00      0.91      0.95        43
      012307       0.95      1.00      0.97        18
      051602       0.92      1.00      0.96        23
      020604       0.78      0.88      0.82         8
      020606       0.83      1.00      0.91         5
      020602       0.88      1.00      0.93        21
      020710       0.83      0.56      0.67        18
      020601       1.00      0.75      0.86         8
      010607       1.00      1.00      1.00        16
        0229       0.98      1.00      0.99       251
      030903       1.00      1.00      1.00         9
      021401       0.88      1.00      0.93        14
      021408       0.92      0.96      0.94        25
      021306       0.79      0.93      0.85        28
      021405       0.88      0.94      0.91        16
      021406       1.00      1.00      1.00         5
      021407       0.93      0.88      0.90        16
      021301       0.92      1.00      0.96        12
      020705       0.96      0.69      0.80        32
      020711       0.86      0.95      0.90        19
      021409       0.80      0.80      0.80         5
      010503       0.85      0.90      0.88        31
      010608       1.00      0.94      0.97        18
      022309       0.75      0.82      0.78        11
        0131       0.99      0.94      0.96        78
        0302       1.00      1.00      1.00       149
      021101       0.56      0.62      0.59         8
      012903       0.93      0.90      0.91        41
      030904       1.00      0.67      0.80         6
      020507       1.00      1.00      1.00        18
      020802       0.96      0.90      0.93        30
      020704       1.00      1.00      1.00        11
      020805       0.94      0.94      0.94        16
      011001       1.00      1.00      1.00        45
        1901       1.00      1.00      1.00         5
        0408       1.00      1.00      1.00        67
      011202       0.89      1.00      0.94        16
      030803       1.00      0.96      0.98        23
      051702       1.00      0.71      0.83         7
      020406       0.72      0.86      0.78        21
      020403       0.88      0.90      0.89        48
      021502       1.00      0.71      0.83         7
      021402       0.89      0.84      0.86        19
      021601       0.95      0.70      0.81        27
      021403       0.88      0.94      0.91        16
      021404       1.00      0.67      0.80         3
      021501       0.94      0.97      0.96        34
      020709       1.00      0.87      0.93        15
      020708       1.00      1.00      1.00         5
      030101       0.92      0.97      0.94        97
      030701       0.90      0.95      0.93        20
      010609       1.00      0.88      0.93         8
      040901       0.93      1.00      0.96        25
      030102       0.94      0.88      0.91        67
      020101       0.75      0.50      0.60         6
      051802       0.97      0.97      0.97        32
      020508       0.70      1.00      0.82         7
      010801       0.93      1.00      0.96        39
      020301       0.93      0.95      0.94       133
      030302       1.00      1.00      1.00        12
      010604       1.00      1.00      1.00         6
      030104       0.96      0.88      0.92        26
        0230       1.00      1.00      1.00        44
      020702       1.00      0.67      0.80         9
      020505       0.92      0.94      0.93        47
      020502       1.00      0.89      0.94        38
      021001       0.75      0.79      0.77        19
      051801       1.00      0.94      0.97        16
      041002       1.00      1.00      1.00         4
        0404       0.00      0.00      0.00         2
      020801       0.76      0.83      0.79        35
        0208       1.00      1.00      1.00         4
      020603       1.00      1.00      1.00         3
      020706       0.80      0.67      0.73         6
      030905       1.00      1.00      1.00         5
      021308       0.86      1.00      0.92         6
      021307       0.93      1.00      0.96        13
      020503       1.00      0.67      0.80         3
      020608       1.00      0.60      0.75         5
        0234       1.00      1.00      1.00         8
      020401       0.79      0.73      0.76        15
        0129       1.00      0.70      0.82        10
      030703       0.67      1.00      0.80         4
      012901       0.88      1.00      0.93         7
      040202       1.00      1.00      1.00        12
      040601       1.00      1.00      1.00         5
      051603       1.00      1.00      1.00         8
      040201       1.00      1.00      1.00         7
      052006       1.00      1.00      1.00         3
      021303       0.75      0.75      0.75         4
      051201       1.00      0.67      0.80         3
      050101       1.00      1.00      1.00         4

    accuracy                           0.95     11876
   macro avg       0.91      0.89      0.90     11876
weighted avg       0.95      0.95      0.95     11876

Class: 0806
Precision: 0.5714285714285714
Recall: 0.8571428571428571
F1-score: 0.6857142857142857
Support: 14.0
-------------------------------
Class: 0813
Precision: 0.5
Recall: 0.3333333333333333
F1-score: 0.4
Support: 6.0
-------------------------------
Class: 0812
Precision: 0.5
Recall: 0.3333333333333333
F1-score: 0.4
Support: 3.0
-------------------------------
Class: 0803
Precision: 0.42857142857142855
Recall: 0.375
F1-score: 0.4
Support: 8.0
-------------------------------
Class: 0818
Precision: 0.5
Recall: 0.4444444444444444
F1-score: 0.47058823529411764
Support: 9.0
-------------------------------
Class: 0815
Precision: 0.5
Recall: 0.5714285714285714
F1-score: 0.5333333333333333
Support: 7.0
-------------------------------
Class: 021101
Precision: 0.5555555555555556
Recall: 0.625
F1-score: 0.5882352941176471
Support: 8.0
-------------------------------
Class: 0404
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Support: 2.0
-------------------------------

In [82]:
conf_mat = confusion_matrix(y_test, y_pred)

In [83]:
from IPython.display import display

for predicted in cat_id_df.cat_id:
    for actual in cat_id_df.cat_id:
        if predicted != actual and conf_mat[actual, predicted] >= 6:
            #print(predicted,actual)
            #print(indices_test[(y_pred == id_to_cat[predicted])  & (y_pred == id_to_cat[predicted]) ])
            print("{} 预测为 {} : {} 例.".format(getClassName(actual), getClassName(predicted), conf_mat[actual, predicted]))
            display(products.loc[indices_test[(y_test == actual) & (y_pred == predicted)]][['ItemClsCode', 'ItemCode','ItemName','preprocessed']])
            print(' ')

020301-陶瓷餐具 预测为 020504-玻璃器皿 : 6 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
40102,020301,6970175116780,瓷纳雅（1152）简约纹理口杯450ml,69701751 瓷纳雅 1152 简约 纹理 口杯 450ml 只 2008 ...
27827,020301,6935706903932,佳得利JDL440-513古韵杯420ml,69357069 佳得利 JDL440513 古韵杯 420ml 只 2008 ...
42347,020301,6971173883216,晋宝源3#焖烧煲 黑色贴花,69711738 晋宝源 3 焖 烧煲 黑色 贴花 只 2008
27811,020301,6935706900894,佳得利JDL116-188色釉束腰镜面陶瓷杯（带盖,69357069 佳得利 JDL116188 色釉 束腰 镜面 陶瓷杯 带盖 只 2...
21668,020301,6927451401047,嘉顺3#焖烧煲3.8L 黑色贴花,69274514 嘉顺 3 焖 烧煲 38L 黑色 贴花 个 2008
32928,020301,6943223355264,贴钻石金JLS-54-5白8件套钻石水具,69432233 贴 钻石 金 JLS545 白 8 件套 钻石 水具 个 2008...

010602-调味酱 预测为 010605-调味料 : 6 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
43044,010602,6971425331540,30g鸿兴源白胡椒粉,69714253 30g 鸿 兴源 白 胡椒粉 包 1017
7398,010602,6902265801719,800g海天豆瓣酱,69022658 800g 海天 豆瓣酱 瓶 1017
20956,010602,6926718450101,草原红太阳纯芝麻酱200G,69267184 草原 红太阳 纯 芝麻酱 200G 瓶 1014
41789,010602,6970974156147,金砖烧烤酱280g,69709741 金砖 烧烤 酱 280g 瓶 1014
42738,010602,6971284204108,海底捞122g麻酱粉,69712842 海底 捞 122g 麻酱 粉 盒 1042
14778,010602,6921317644135,味好美沙拉酱,69213176 味好 美 沙拉酱 瓶 1016

1502-文具用品 预测为 1501-玩具 : 16 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
35379,1502,6948764238755,水滴拍拍灯,69487642 水滴 拍拍 灯 个 3006
46289,1502,6973286784312,小麦手帐素材大礼包荞荞,69732867 小麦 手帐 素材 大礼包 荞荞 个 3006
39545,1502,6959316128196,2819A展达小兔面条机,69593161 2819A 展达 小兔 面条机 个 3006
29738,1502,6937855701056,星火打气筒105,69378557 星火 打气筒 105 个 3006
37517,1502,6953706403573,大颗粒宝宝按摩球,69537064 大 颗粒 宝宝 按摩 球 个 3006
47404,1502,6974265361371,雅斯妮106硅胶印章套装,69742653 雅斯 妮 106 硅胶 印章 套装 个 3006
49625,1502,6985643785320,创意手账贴,69856437 创意 手账 贴 个 3006
28344,1502,6936447700774,波斯猫学具盒套装,69364477 波斯猫 学具 盒 套装 个 3006
20923,1502,6926679230378,哈尼兔挂钩迷你封口机,69266792 哈尼 兔 挂钩 迷你 封口机 个 3006
46290,1502,6973286785814,小麦新年礼盒,69732867 小麦 新年 礼盒 个 3006
32673,1502,6942310506510,兴利201不干胶/蓝,69423105 兴利 201 不干胶 蓝 个 3006
40522,1502,6970258511815,泡泡枪,69702585 泡泡 枪 个 3006
20922,1502,6926679230057,有个果子君橘子捏捏乐,69266792 有个 果子 君 橘子 捏 捏 乐 个 3006
28984,1502,6936770883205,海底乐园80#,69367708 海底 乐园 80 个 3006
45518,1502,6972886701798,可瑞乐软萌小钱包,69728867 可瑞乐 软萌 小 钱包 个 3006
49544,1502,6978242100113,萌憨憨出去玩鸭,69782421 萌憨 憨 出去玩 鸭 个 3006

012302-饼干 预测为 012301-膨化食品 : 6 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
13908,012302,6920907807998,磨古力曲奇 黄油,69209078 磨 古力 曲奇 黄油 盒 1042
20620,012302,6926419102224,苏琪小脆（椒麻味）,69264191 苏琪 小脆 椒 麻味 袋 1001
20212,012302,6925927490724,丫丫虾肉饼100g（原味）,69259274 丫丫 虾 肉饼 100g 原味 袋 1047
20211,012302,6925927490717,丫丫虾肉饼200g（原味）,69259274 丫丫 虾 肉饼 200g 原味 袋 1047
20213,012302,6925927491561,丫丫虾肉饼180g（咸味）,69259274 丫丫 虾 肉饼 180g 咸味 袋 1047
14909,012302,6921482334022,旺旺泡芙 牛奶,69214823 旺旺 泡 芙 牛奶 袋 1038

010602-调味酱 预测为 010702-瓶装酱菜 : 6 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
19796,010602,6925414741292,宏腾烧椒辣椒酱280g,69254147 宏腾 烧椒 辣椒酱 280g 瓶 1014
47640,010602,6974371261732,巧娘懂味道香菇肉酱,69743712 巧娘 懂 味道 香菇 肉酱 瓶 1015
25910,010602,6933749013861,鲜吉多牦牛肉酱,69337490 鲜吉多 牦牛 肉酱 瓶 1003
44380,010602,6972068531205,巧娘下饭麻辣酱,69720685 巧娘 下饭 麻辣酱 瓶 1015
21146,010602,6926896704140,吉香居麻辣酱,69268967 吉香居 麻辣酱 瓶 1016
18407,010602,6924116181276,260g麻辣三师蒜香王,69241161 260g 麻辣 三师 蒜 香王 瓶 1017

020504-玻璃器皿 预测为 020301-陶瓷餐具 : 8 例.

,ItemClsCode,ItemCode,ItemName,preprocessed
42314,020504,6971173880048,晋宝源2号介杯160321160412,69711738 晋宝源 2 号 介杯 160321160412 只 2008 ...
33862,020504,6945794464185,顺祥缤纷大号维雅双耳保鲜碗800ML,69457944 顺祥 缤纷 大号 维雅 双耳 保鲜 碗 800ML 只 2008 ...
43807,020504,6971875906022,爱诗格尔AS-CF01/L4厨妃四件套,69718759 爱 诗格尔 ASCF01L4 厨妃 四件套 只 2008
42421,020504,6971173885623,晋宝源锤纹杯（喷蓝色）（小）JBY-18045,69711738 晋宝源 锤 纹杯 喷 蓝色 小 JBY18045 只 2008 ...
42429,020504,6971173885876,晋宝源中号描金色拉玻璃碗700MLHY002,69711738 晋宝源 中 号 描金 色拉 玻璃碗 700MLHY002 只 20...
42417,020504,6971173885531,晋宝源小雏菊锤纹杯（直）JBY-18046,69711738 晋宝源 小 雏菊 锤纹杯 直 JBY18046 只 2008 ...
34189,020504,6947094110687,冠祥新中式兰花水具套装,69470941 冠祥 新 中式 兰花 水具 套装 套 2008
47486,020504,6974350261487,晋宝源唐古拉圆形锤纹玻璃彩碗195cm,69743502 晋宝源 唐古拉 圆形 锤纹 玻璃 彩碗 195cm 只 2008 ...

In [84]:
from sklearn.feature_selection import chi2
import shutil
import codecs
import os

print('*' * 80)
print('Outputting model in human readable format')
output_dir = 'm_key_words'
shutil.rmtree(output_dir, ignore_errors=True)
os.mkdir(output_dir)

N = 10
for cat, cat_id in sorted(cat_to_id.items()):
    features_chi2 = chi2(X, y == cat_id)
    indices = np.argsort(features_chi2[0])
    feature_names = np.array(vectorizer.get_feature_names_out())[indices]
    unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
    bigrams = [v for v in feature_names if len(v.split(' ')) == 2]
    output_path = os.path.join(output_dir, '%s.txt' % cat)
    with codecs.open(output_path, encoding='utf-8', mode='w') as f:
        #print("# '{}':".format(cat), file=f)
        print("# '{}':".format(getClassName(cat_id)), file=f)
        print("  . 最相关单词语:\n       . {}".format('\n       . '.join(unigrams[-N:])), file=f)
        print("  . 最相关单词语组合:\n       . {}".format('\n       . '.join(bigrams[-N:])), file=f)

********************************************************************************
Outputting model in human readable format